-- MySQL Script generated by MySQL Workbench
-- Tue Mar 25 18:05:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema robiot
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `robiot` ;

-- -----------------------------------------------------
-- Schema robiot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `robiot` DEFAULT CHARACTER SET utf8 ;
USE `robiot` ;

-- -----------------------------------------------------
-- Table `robiot`.`Erabiltzaileak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `robiot`.`Erabiltzaileak` (
  `idErabiltzaileak` INT NOT NULL AUTO_INCREMENT,
  `Izen` VARCHAR(45) NOT NULL,
  `Abizena` VARCHAR(45) NULL,
  `Pasahitza` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Hegan_egiteko_baimena` VARCHAR(16) NULL,
  PRIMARY KEY (`idErabiltzaileak`),
  UNIQUE INDEX `Izen_UNIQUE` (`Izen` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `robiot`.`Droneak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `robiot`.`Droneak` (
  `idDroneak` INT NOT NULL AUTO_INCREMENT,
  `Izena` VARCHAR(45) NOT NULL,
  `Mota` VARCHAR(45) NOT NULL,
  `Deskribapena` VARCHAR(45) NULL,
  PRIMARY KEY (`idDroneak`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `robiot`.`Baimenak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `robiot`.`Baimenak` (
  `idBaimenak` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idBaimenak`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `robiot`.`Partekatzeak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `robiot`.`Partekatzeak` (
  `idPartekatzeak` INT NOT NULL,
  `Erabiltzaileak_idErabiltzaileak` INT NOT NULL,
  `Droneak_idDroneak` INT NOT NULL,
  `Baimenak_idBaimenak` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idPartekatzeak`),
  INDEX `fk_Partekatzeak_Erabiltzaileak_idx` (`Erabiltzaileak_idErabiltzaileak` ASC) VISIBLE,
  INDEX `fk_Partekatzeak_Droneak1_idx` (`Droneak_idDroneak` ASC) VISIBLE,
  INDEX `fk_Partekatzeak_Baimenak1_idx` (`Baimenak_idBaimenak` ASC) VISIBLE,
  CONSTRAINT `fk_Partekatzeak_Erabiltzaileak`
    FOREIGN KEY (`Erabiltzaileak_idErabiltzaileak`)
    REFERENCES `robiot`.`Erabiltzaileak` (`idErabiltzaileak`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partekatzeak_Droneak1`
    FOREIGN KEY (`Droneak_idDroneak`)
    REFERENCES `robiot`.`Droneak` (`idDroneak`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partekatzeak_Baimenak1`
    FOREIGN KEY (`Baimenak_idBaimenak`)
    REFERENCES `robiot`.`Baimenak` (`idBaimenak`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `robiot`.`Sentsoreak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `robiot`.`Sentsoreak` (
  `idSentsoreak` INT NOT NULL AUTO_INCREMENT,
  `Izena` VARCHAR(45) NOT NULL,
  `Mota` VARCHAR(45) NULL,
  `Deskribapena` VARCHAR(45) NULL,
  PRIMARY KEY (`idSentsoreak`),
  UNIQUE INDEX `Izena_UNIQUE` (`Izena` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `robiot`.`Drone_Sentsore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `robiot`.`Drone_Sentsore` (
  `idDroneSentsore` INT NOT NULL AUTO_INCREMENT,
  `Ezizena` VARCHAR(45) NULL,
  `Droneak_idDroneak` INT NOT NULL,
  `Sentsoreak_idSentsoreak` INT NOT NULL,
  PRIMARY KEY (`idDroneSentsore`),
  INDEX `fk_DroneSentsore_Droneak1_idx` (`Droneak_idDroneak` ASC) VISIBLE,
  INDEX `fk_DroneSentsore_Sentsoreak1_idx` (`Sentsoreak_idSentsoreak` ASC) VISIBLE,
  CONSTRAINT `fk_DroneSentsore_Droneak1`
    FOREIGN KEY (`Droneak_idDroneak`)
    REFERENCES `robiot`.`Droneak` (`idDroneak`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DroneSentsore_Sentsoreak1`
    FOREIGN KEY (`Sentsoreak_idSentsoreak`)
    REFERENCES `robiot`.`Sentsoreak` (`idSentsoreak`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `robiot`.`GPS_kokapena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `robiot`.`GPS_kokapena` (
  `idGPS_kokapena` INT NOT NULL,
  `Droneak_idDroneak` INT NOT NULL,
  `Longitude` FLOAT NULL,
  `Latitude` FLOAT NULL,
  `Altitude` FLOAT NULL,
  `Timestamp` TIMESTAMP(6) NULL,
  `Noranzkoa` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idGPS_kokapena`),
  INDEX `fk_GPS_kokapena_Droneak1_idx` (`Droneak_idDroneak` ASC) VISIBLE,
  CONSTRAINT `fk_GPS_kokapena_Droneak1`
    FOREIGN KEY (`Droneak_idDroneak`)
    REFERENCES `robiot`.`Droneak` (`idDroneak`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `robiot`.`Mezuak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `robiot`.`Mezuak` (
  `idMezuak` INT NOT NULL AUTO_INCREMENT,
  `Droneak_idDroneak` INT NOT NULL,
  `Edukia` VARCHAR(200) NULL,
  `Timestamp` TIMESTAMP(6) NULL,
  `Noranzkoa` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idMezuak`),
  INDEX `fk_Mezuak_Droneak1_idx` (`Droneak_idDroneak` ASC) VISIBLE,
  CONSTRAINT `fk_Mezuak_Droneak1`
    FOREIGN KEY (`Droneak_idDroneak`)
    REFERENCES `robiot`.`Droneak` (`idDroneak`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `robiot`.`Sentsore_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `robiot`.`Sentsore_info` (
  `idSentsore_info` INT NOT NULL AUTO_INCREMENT,
  `Drone_Sentsore_idDroneSentsore` INT NOT NULL,
  `Balioa` VARCHAR(45) NULL,
  `Timestamp` TIMESTAMP(6) NULL,
  PRIMARY KEY (`idSentsore_info`),
  INDEX `fk_Sentsore_info_Drone_Sentsore1_idx` (`Drone_Sentsore_idDroneSentsore` ASC) VISIBLE,
  CONSTRAINT `fk_Sentsore_info_Drone_Sentsore1`
    FOREIGN KEY (`Drone_Sentsore_idDroneSentsore`)
    REFERENCES `robiot`.`Drone_Sentsore` (`idDroneSentsore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `robiot`.`Baimenak`
-- -----------------------------------------------------
START TRANSACTION;
USE `robiot`;
INSERT INTO `robiot`.`Baimenak` (`idBaimenak`) VALUES ('Admin');
INSERT INTO `robiot`.`Baimenak` (`idBaimenak`) VALUES ('Jabea');
INSERT INTO `robiot`.`Baimenak` (`idBaimenak`) VALUES ('Kontrolatu');
INSERT INTO `robiot`.`Baimenak` (`idBaimenak`) VALUES ('Ikusi');

COMMIT;

